sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  alioss:
    access-key-id: LTAI5t7owtgTt76mDREfYvCu
    access-key-secret: Rw8una4EFH3izCDWR5F9zJIJJWYyyh
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucket-name: web-frameworkjn131

  redis:
    host: localhost
    port: 6379

  wechat:
    appid: wx4e71fa520413f703
    secret: a6d61c9e0f5c716d7e688b2a42c03a1f